/* text array */

var textArray = ["You are attached to your smartphone.",
    "You default to screen time in your downtime.",
    "You're afraid of silence.",
    "Phone calls aren't your communication of preference.",
    "You believe in multitasking.",
    "You can’t make up your mind.",
    "You grab the closest device when left alone.",
    "You’re worried you’re missing out.",
    "Being away from your phone makes you anxious.",
    "Your self-esteem has taken a hit.",
    "You sleep with your phone.",
    "You feel less connected.",
    "Social media makes you feel negative about your own life.",
    "You check your email and/or social feeds throughout every meal.",
    "You can’t function when your phone dies.",
    "You keep bumping into things.",
    "You can’t make up your mind.",
    "Your vision goes blurry after looking at a screen.",
    "You never read an article from beginning to end.",
    "Your thumb on your dominant hand is sore from all the scrolling.",
    "You look at your phone first thing when you wake up.",
    "You get a bit twitchy and anxious if separated from your phone.",
    "You get panicked when the battery is running low.",
    "You are feeling hurried and lacking in concentration.",
    "You feel uninspired by your social media output.",
    "You waste hours online when you should be doing other things.",
    "You check your mobile phone in the bathroom.",
    "You shoo away, or ignore friends, colleagues or family members while you are on your devices.",
    "You break out in a sweat if you forget your phone or iPad.",
    "The first thing you do in the morning is check your smart phone or laptop.",
    "You email or text back and forth with someone who is sitting in the next room.",
    "You wake up in the middle of the night and check and respond to your email and social media accounts.",
    "You check your email during a movie.",
    "You’re clumsy.",
    "Social media is detrimental to your personal worth.",
    "You check your phone or tablet for social media updates and emails before breakfast.",
    "You feel a sense of panic or anxiety if you don’t have your phone with you at all times.",
    "You take photos of your food before eating.",
    "You haven’t bought anything in a physical shop, rather than online, for six months.",
    "You have sore, bruised, or raw thumbs from texting so much.",
    "You get very anxious if you are away from your phone for more than two minutes.",
    "You want to put a hashtag before every word.",
    "You check your phone before you even get out of bed.",
    "You Instagram all your food.",
    "Your phone is always out of your pocket.",
    "Your days begin and end with the infinite scrolling of news feeds and social updates.",
    "You respond to text messages instantly.",
    "Your smartphone always finds a way to the dinner table and toilet seat.",
    "You and your smartphone share the same bed.",
    "You panic when you see the low battery warning.",
    "You often find yourself thinking about going online.",
    "You find yourself spending longer and longer periods of time online.",
    "You go online to lift your mood or escape your problems.",
    "You feel cranky, sad, annoyed or irritable when you’re not online.",
    "You’ve lost interest in activities and hobbies that you used to like.",
    "You neglect your health and sleep because of your internet or gaming use.",
    "You’ve lost or jeopardised your relationship, job or studies because of your internet or gaming use.",
    "You’ve covered up or lied about your internet or gaming use.",
    "You continue going online or gaming despite it causing problems in your relationships.",
    "You’re no longer getting enough sleep.",
    "You have lost awareness of your surroundings.",
    "You’re hearing ‘phantom vibrations’.",
    "The thought of losing your phone makes you uneasy.",
    "You sleep with your phone and check it during meals.",
    "You answer your phone during intimate partner moments.",
    "Journeys pass you by.",
    "You can’t walk in a straight line."
 ];
